### ISSUE TITLE
Works not right with plugin Carz

### ISSUE THREAD

**Issue by haohaostudio** [hornta/racing#50]
When players launch the engine, Racing shut it down.
https://vimeo.com/405717153

**Comment by hornta** [comment]
@haohaostudio Alright so Carz have changed since last time I used it. Now it requires you to hold and punch a stick in the air to start it. 
But when the player is punching in the air they will automatically be respawned in their last checkpoint(or the startpoint if the have not passed any checkpoint) to avoid getting stuck.

**Comment by hornta** [comment]
I released the 1.27.1 version now that fixes so you can punch right click the stick to start the motor.
